-- 02_staging.sql: typed copy of raw.orders. Safe to re-run.
DROP TABLE IF EXISTS staging.orders;

CREATE TABLE staging.orders (
    type                         TEXT,
    days_for_shipping_real       INTEGER,
    days_for_shipment_scheduled  INTEGER,
    delivery_status              TEXT,
    late_delivery_risk           SMALLINT,
    category_id                  INTEGER,
    category_name                TEXT,
    customer_city                TEXT,
    customer_country             TEXT,
    customer_id                  INTEGER,
    customer_segment             TEXT,
    customer_state               TEXT,
    customer_zipcode             TEXT,       -- not used for math, so TEXT
    department_id                INTEGER,
    department_name              TEXT,
    latitude                     NUMERIC,
    longitude                    NUMERIC,
    market                       TEXT,
    order_city                   TEXT,
    order_country                TEXT,
    order_customer_id            INTEGER,
    order_date                   TIMESTAMP,
    order_id                     INTEGER,
    order_item_cardprod_id       INTEGER,
    order_item_discount          NUMERIC,
    order_item_discount_rate     NUMERIC,
    order_item_id                INTEGER PRIMARY KEY,
    order_item_product_price     NUMERIC,
    order_item_profit_ratio      NUMERIC,
    order_item_quantity          INTEGER,
    sales                        NUMERIC,
    order_item_total             NUMERIC,
    order_profit_per_order       NUMERIC,
    order_region                 TEXT,
    order_state                  TEXT,
    order_status                 TEXT,
    product_card_id              INTEGER,
    product_category_id          INTEGER,
    product_image                TEXT,
    product_name                 TEXT,
    product_price                NUMERIC,
    shipping_date                TIMESTAMP,
    shipping_mode                TEXT,
    is_late                      SMALLINT,
    is_eligible                  SMALLINT,
    is_on_time                   SMALLINT,
    order_to_ship_days           INTEGER
);

INSERT INTO staging.orders
SELECT
    type,
    days_for_shipping_real::INTEGER,
    days_for_shipment_scheduled::INTEGER,
    delivery_status,
    late_delivery_risk::SMALLINT,
    category_id::INTEGER,
    category_name,
    customer_city,
    customer_country,
    customer_id::INTEGER,
    customer_segment,
    customer_state,
    regexp_replace(customer_zipcode, '\.0$', ''),   -- drop a trailing ".0" if present
    department_id::INTEGER,
    department_name,
    latitude::NUMERIC,
    longitude::NUMERIC,
    market,
    order_city,
    order_country,
    order_customer_id::INTEGER,
    order_date::TIMESTAMP,
    order_id::INTEGER,
    order_item_cardprod_id::INTEGER,
    order_item_discount::NUMERIC,
    order_item_discount_rate::NUMERIC,
    order_item_id::INTEGER,
    order_item_product_price::NUMERIC,
    order_item_profit_ratio::NUMERIC,
    order_item_quantity::INTEGER,
    sales::NUMERIC,
    order_item_total::NUMERIC,
    order_profit_per_order::NUMERIC,
    order_region,
    order_state,
    order_status,
    product_card_id::INTEGER,
    product_category_id::INTEGER,
    product_image,
    product_name,
    product_price::NUMERIC,
    shipping_date::TIMESTAMP,
    shipping_mode,
    is_late::SMALLINT,
    is_eligible::SMALLINT,
    is_on_time::SMALLINT,
    order_to_ship_days::INTEGER
FROM raw.orders;